# Generated by Django 3.2.2 on 2021-05-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_order_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.CharField(default=None, max_length=300),
            preserve_default=False,
        ),
    ]
