# Generated by Django 3.2.2 on 2021-05-08 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_store_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='seller.store'),
            preserve_default=False,
        ),
    ]
