# Generated by Django 3.2.2 on 2021-05-09 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_auto_20210508_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='store',
        ),
        migrations.AddField(
            model_name='category',
            name='store',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='seller.store'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='link',
            field=models.CharField(default='', max_length=400),
        ),
    ]
